### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by HandyJoshua** [turboflakes/crunch#62]
Hey there i'm having issue on building up crunch docker image. 

On different istances i have a huge use of ram and resources and ofetn the system shutdown

Someone can suggest me a pre build with cargo? or any other solution? thank you in advance

**Comment by paulormart** [comment]
Hey can you pull latest from `main` branch and try `docker build -t localhost/crunch -f Dockerfile.alpine .`?

This specific [dockerfile](https://github.com/turboflakes/crunch/blob/main/Dockerfile.alpine) will just build a docker container where it downloads the latest pre-built Alpine binary in the release, so it doesn't take your computer resources to build the project from source.

**Comment by HandyJoshua** [comment]
Thank you! @paulormart Now is way faster. 

Now i have another problem... 
I'm using docker-compose.yaml as this to better handle multiple images. 

Seems latest crunch don't want to start 

```
version: '3'
services:
  crunch:
    image: localhost/crunch:latest
    volumes:
      - ./.env:/.env
      - ./.private.seed:/.private.seed
    command: rewards

```

ERROR
```

 [2025-06-12T10:03:23Z INFO  crunch::runtimes::kusama] Inspect and `crunch` unclaimed payout rewards
crunch-1  | [2025-06-12T10:03:23Z ERROR crunch::crunch] IOError error: No such file or directory (os error 2)
```

Files are correctly locally set

**Comment by paulormart** [comment]
Better to have the configuration _paths_ explicitly set as in the example:

```
version: "3"
services:
  crunch:
    image: localhost/crunch:latest
    volumes:
      - ./.env:/.env
      - ./.private.seed:/.private.seed
    command: --config-path /.env polkadot rewards daily -f /.private.seed
```
